Repository maistra/test-infra, pull requests merged in 2020-07, with the labels that each got.

#53 Move 1.2 jobs to 2.0 branch
  prow/config.gen.yaml
  prow/config/presubmits.yaml
Labels: okay to merge, size/S

#54 MAISTRA-1628: Add linter check on presubmit for maistra/istio
  Makefile
  docker/maistra-builder_2.0.Dockerfile
  docker/scripts/install_docs_tools.sh
  prow/config.gen.yaml
  prow/config/presubmits.yaml
Labels: okay to merge, size/L

#55 MAISTRA-1634: Add gen-check presubmit test for maistra/istio
  docker/maistra-builder_2.0.Dockerfile
  prow/config.gen.yaml
  prow/config/presubmits.yaml
Labels: okay to merge, size/M

#56 MAISTRA-1634: Install tools needed by `maistra-gen-k8s-client` target
  docker/maistra-builder_2.0.Dockerfile
Labels: okay to merge, size/S

#57 MAISTRA-1634: Add more tools needed for `make gen`
  docker/maistra-builder_2.0.Dockerfile
Labels: okay to merge, size/S

#47 Speed up build-containers job
  Makefile
Labels: okay to merge, size/XS

#58 MAISTRA-1648: Add a prow presubmit job for maistra/proxy
  Makefile
  docker/maistra-proxy-builder_2.0.Dockerfile
  prow/config.gen.yaml
  prow/config/postsubmits.yaml
  prow/config/presubmits.yaml
  prow/plugins.yaml
Labels: okay to merge, size/L

#59 Trigger proxy image build
  docker/maistra-proxy-builder_2.0.Dockerfile
Labels: okay to merge, size/XS

#61 Make sure to trigger container build when script dir is changed
  prow/config.gen.yaml
  prow/config/postsubmits.yaml
  prow/config/presubmits.yaml
Labels: okay to merge, size/XS

#62 MAISTRA-1651: Update proxy on Envoy postsubmit
  prow/config.gen.yaml
  prow/config/postsubmits.yaml
  prow/plugins.yaml
Labels: okay to merge, size/M

#63 MAISTRA-1651: Install tools in proxy image needed by automator
  docker/maistra-proxy-builder_2.0.Dockerfile
Labels: okay to merge, size/S

#64 MAISTRA-1661: Bump prow
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/plank_deployment.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/config.gen.yaml
  prow/config/plank.yaml
Labels: okay to merge, size/M

#65 Update for maistra 2.0
  prow/config.gen.yaml
  prow/config/postsubmits.yaml
  prow/config/presubmits.yaml
Labels: okay to merge, size/M
