Repository maistra/test-infra, pull requests merged in 2020-12, with the labels that each got.

#89 Configure istio to use tide
  prow/config.gen.yaml
  prow/config/branch-protection.yaml
  prow/config/tide.yaml
  prow/plugins.yaml
Labels: okay to merge, size/S

#96 Do not squash PR's based on labels
  prow/config.gen.yaml
  prow/config/tide.yaml
Labels: okay to merge, size/XS

#97 Bump prow
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/plank_deployment.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/config.gen.yaml
  prow/config/plank.yaml
Labels: okay to merge, size/M

#98 Bump k8s test-infra tools to match deployed version
  docker/maistra-builder_2.0.Dockerfile
  docker/maistra-proxy-builder_1.1.Dockerfile
  docker/maistra-proxy-builder_2.0.Dockerfile
Labels: don't squash, okay to merge, size/M

#99 Change references to 1.2 images to 2.0
  docker/maistra-builder_1.2.Dockerfile
  prow/config.gen.yaml
  prow/config/postsubmits.yaml
  prow/config/presubmits.yaml
Labels: okay to merge, size/L

#100 Bump dockerfiles too
  docker/maistra-builder_2.0.Dockerfile
  docker/maistra-proxy-builder_1.1.Dockerfile
  docker/maistra-proxy-builder_2.0.Dockerfile
  tools/bump_prow.sh
Labels: don't squash, okay to merge, size/S

#101 Add tide to other maistra repos
  prow/config.gen.yaml
  prow/config/tide.yaml
  prow/plugins.yaml
Labels: okay to merge, size/M

#102 Remove broken post-submit jobs
  prow/config.gen.yaml
  prow/config/postsubmits.yaml
Labels: okay to merge, size/L

#103 Fix docker tools location
  docker/maistra-builder_2.0.Dockerfile
Labels: okay to merge, size/XS

#104 Use docker-ce, not moby for 2.0
  docker/maistra-builder_2.0.Dockerfile
Labels: okay to merge, size/XS

#105 Add support for maistra/istio's maistra-2.1 branch
  Makefile
  docker/maistra-builder_2.1.Dockerfile
  prow/config.gen.yaml
  prow/config/presubmits.yaml
Labels: okay to merge, size/L

#108 Run two replicas of deck
  prow/cluster/deck_deployment.yaml
Labels: okay to merge, size/XS

#109 Update ProwJob CRD to latest version
  prow/cluster/prowjob_customresourcedefinition.yaml
Labels: okay to merge, size/XS

#106 Fix 2.1 branch
  docker/maistra-builder_2.1.Dockerfile
  prow/config.gen.yaml
  prow/config/presubmits.yaml
Labels: okay to merge, size/XS

#110 Fix container pushing and drop old containers
  Makefile
  docker/maistra-builder_1.0.Dockerfile
  docker/maistra-builder_1.1.Dockerfile
  docker/scripts/README.md
  docker/scripts/install_base.sh
  docker/scripts/install_docker.sh
  docker/scripts/install_docs_tools.sh
  docker/scripts/install_go_12.sh
  docker/scripts/install_go_13.sh
  docker/scripts/install_helm.sh
  docker/scripts/install_kubectl.sh
  docker/scripts/install_shellcheck.sh
Labels: okay to merge, size/L

#111 Fix push
  Makefile
  docker/maistra-builder_2.0.Dockerfile
Labels: okay to merge, size/XS

#112 Fix gen-check job execution on 2.1 build image
  docker/maistra-builder_2.1.Dockerfile
Labels: okay to merge, size/XS

#113 Add istio-operator 2.1 jobs
  prow/config.gen.yaml
  prow/config/presubmits.yaml
Labels: okay to merge, size/M

#114 Install both yq's using different names
  docker/maistra-builder_2.0.Dockerfile
  docker/maistra-builder_2.1.Dockerfile
Labels: okay to merge, size/XS
