Repository maistra/test-infra, pull requests merged in 2020-08, with the labels that each got.

#66 Use official bazel binary
  docker/maistra-proxy-builder_2.0.Dockerfile
Labels: okay to merge, size/XS

#67 Add max_concurreny options to jobs with high resource usage
  prow/config.gen.yaml
  prow/config/presubmits.yaml
Labels: okay to merge, size/S

#68 Add resource limits/requests to jobs
  Makefile
  prow/config.gen.yaml
  prow/config/postsubmits.yaml
  prow/config/presubmits.yaml
  scripts/check-resource-limits.sh
Labels: okay to merge, size/L

#69 Add Envoy 1.1 job
  prow/config.gen.yaml
  prow/config/presubmits.yaml
Labels: okay to merge, size/M
