Repository maistra/test-infra, pull requests merged in 2020-05, with the labels that each got.

#26 Remove always_run property when run_if_changed is in use
  prow/config.gen.yaml
  prow/config/postsubmits.yaml
  prow/config/presubmits.yaml
Labels: size/XS

#27 Add prow's checkconfig to the builder image
  docker/maistra-builder_1.2.Dockerfile
Labels: size/XS

#28 Use 1.2 builder image for test-infra jobs
  prow/config.gen.yaml
  prow/config/postsubmits.yaml
  prow/config/presubmits.yaml
Labels: size/S

#29 Run checkconfig as part of lint presubmit job
  Makefile
Labels: size/XS

#20 Add automator
  tools/automator.sh
Labels: size/L

#31 Add bump_prow.sh helper script and use it to bump prow images
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/plank_deployment.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/config.gen.yaml
  prow/config/plank.yaml
  tools/bump_prow.sh
Labels: size/L

#30 added license
  LICENSE
Labels: size/L

#32 Add ior jobs
  prow/config.gen.yaml
  prow/config/postsubmits.yaml
  prow/config/presets.yaml
  prow/config/presubmits.yaml
  prow/config/tide.yaml
  prow/plugins.yaml
Labels: size/L

#34 Add COPR token instructions on README
  README.md
Labels: size/XS

#33 Fix the path to automator script
  prow/config.gen.yaml
  prow/config/postsubmits.yaml
Labels: size/XS

#35 Enable tide on test-infra
  prow/config.gen.yaml
  prow/config/tide.yaml
  prow/plugins.yaml
Labels: size/XS

#36 Add istio-operator jobs
  prow/config.gen.yaml
  prow/config/postsubmits.yaml
  prow/config/presubmits.yaml
  prow/config/tide.yaml
  prow/plugins.yaml
Labels: okay to merge, size/L

#37 Automator: support multiple repos
  tools/automator.sh
Labels: okay to merge, size/M

#38 Add rpm-common jobs
  prow/config.gen.yaml
  prow/config/postsubmits.yaml
  prow/config/presubmits.yaml
  prow/plugins.yaml
Labels: okay to merge, size/M

#39 Add tide to rpm-common
  prow/config.gen.yaml
  prow/config/tide.yaml
Labels: okay to merge, size/XS

#40 Unique fork name
  prow/config.gen.yaml
  prow/config/postsubmits.yaml
  tools/automator.sh
Labels: okay to merge, size/S

#41 Update dockerfile to use exect hugo version
  docker/maistra-builder_1.2.Dockerfile
Labels: okay to merge, size/XS

#43 Add prow presubmits for Maistra 1.2 branches
  prow/config.gen.yaml
  prow/config/presubmits.yaml
Labels: okay to merge, size/M

#44 Enable verbose output on istio-operator unittests job
  prow/config.gen.yaml
  prow/config/presubmits.yaml
Labels: okay to merge, size/XS

#45 Rename unit test job for maistra-1.2 branch
  prow/config.gen.yaml
  prow/config/presubmits.yaml
Labels: okay to merge, size/M
