Repository maistra/test-infra, pull requests merged in 2020-04, with the labels that each got.

#8 Update README.md to be more helpful
  README.md
Labels: size/M

#7 Automatically update prow configuration when PRs merge
  README.md
  docker/maistra-builder_1.1.Dockerfile
  docker/scripts/install_kubectl.sh
  prow/config.gen.yaml
  prow/config/postsubmits.yaml
  prow/config/presets.yaml
  prow/create.sh
  prow/setup-prow-deployer.sh
Labels: size/L

#9 Build and push images to quay.io on every commit
  Makefile
  docker/maistra-builder_1.1.Dockerfile
  docker/scripts/entrypoint.sh
  docker/scripts/install_base.sh
  docker/scripts/install_docker.sh
  prow/config.gen.yaml
  prow/config/postsubmits.yaml
  prow/config/presets.yaml
  prow/config/presubmits.yaml
  prow/create.sh
Labels: size/L

#12 Add spelling checker and link checker
  docker/maistra-builder_1.1.Dockerfile
  docker/scripts/install_docs_tools.sh
  prow/config.gen.yaml
  prow/config/presubmits.yaml
  prow/gen-config.sh
Labels: size/M

#14 Enable jobs against maistra-1.2 branch of istio-operator
  prow/config.gen.yaml
  prow/config/presubmits.yaml
Labels: size/XS

#13 Updated plugins.yaml and added maistra-1.1
  prow/config.gen.yaml
  prow/config/presubmits.yaml
  prow/plugins.yaml
Labels: size/XS

#11 Build operator before run the tests
  prow/config.gen.yaml
  prow/config/presubmits.yaml
Labels: size/XS

#18 Miscelaneous fixes
  README.md
  prow/cluster/crier_rbac.yaml
  prow/create.sh
  prow/setup-prow-deployer.sh
  prow/update.sh
Labels: size/M

#19 Create the 1.2 builder image
  Makefile
  docker/maistra-builder_1.2.Dockerfile
  docker/scripts/README.md
Labels: size/M

#15 Add cherrypicker and enable for all Maistra repositories
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/cherrypicker_service.yaml
  prow/plugins.yaml
Labels: size/M

#21 Add lint
  Makefile
  docker/scripts/entrypoint.sh
  prow/config.gen.yaml
  prow/config/presubmits.yaml
  prow/gen-config.sh
  prow/update.sh
Labels: size/M

#17 Bump prow version
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/plank_deployment.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
Labels: size/S

#23 Fix the dockerd args, they cannot be '' when empty
  docker/scripts/entrypoint.sh
Labels: size/XS

#25 Add test for docker support, fix maistra-builder:1.2
  Makefile
  docker/maistra-builder_1.2.Dockerfile
  prow/config.gen.yaml
  prow/config/presubmits.yaml
Labels: size/S

#24 Run certain jobs only when necessary
  prow/config.gen.yaml
  prow/config/postsubmits.yaml
  prow/config/presubmits.yaml
Labels: size/XS
