Repository maistra/test-infra, pull requests merged in 2020-09, with the labels that each got.

#70 Add image for Envoy 1.1
  Makefile
  docker/maistra-proxy-builder_1.1.Dockerfile
Labels: okay to merge, size/M

#71 Enhance 2.0 proxy image so that it can build Envoy as well
  docker/maistra-proxy-builder_2.0.Dockerfile
Labels: okay to merge, size/XS

#72 Add Envoy 2.0 job
  prow/config.gen.yaml
  prow/config/presubmits.yaml
Labels: okay to merge, size/M

#73 Increase timeout for proxy and envoy jobs (4h -> 5h)
  prow/config.gen.yaml
  prow/config/presubmits.yaml
Labels: okay to merge, size/S

#74 Bump prow version
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/plank_deployment.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/config.gen.yaml
  prow/config/plank.yaml
Labels: okay to merge, size/M

#75 Remove unexistent arguments
  prow/cluster/deck_deployment.yaml
  prow/cluster/plank_deployment.yaml
  prow/config.gen.yaml
  prow/config/deck.yaml
Labels: okay to merge, size/S

#76 Increase proxy resources
  prow/config.gen.yaml
  prow/config/presubmits.yaml
Labels: okay to merge, size/M

#78 Revert "Increase proxy resources (#76)"
  prow/config.gen.yaml
  prow/config/presubmits.yaml
Labels: okay to merge

#79 Fix 1.1 container build
  docker/scripts/install_docker.sh
Labels: okay to merge, size/XS

#80 Tide: Auto merge proxy automated PR's
  prow/config.gen.yaml
  prow/config/tide.yaml
Labels: okay to merge, size/XS

#81 Add tide to proxy and envoy repos
  prow/config.gen.yaml
  prow/config/tide.yaml
Labels: okay to merge, size/XS

#77 WASM Extension example
  docker/maistra-builder_2.0.Dockerfile
  prow/config.gen.yaml
  prow/config/postsubmits.yaml
  prow/config/presubmits.yaml
  prow/plugins.yaml
Labels: okay to merge, size/L
