Repository maistra/test-infra, pull requests merged in 2020-10, with the labels that each got.

#83 Update istio when proxy changes
  docker/maistra-proxy-builder_2.0.Dockerfile
  prow/config.gen.yaml
  prow/config/postsubmits.yaml
  prow/config/presets.yaml
  prow/config/presubmits.yaml
  tools/automator.sh
Labels: okay to merge, size/L

#84 Install both yqv2 and yqv3
  docker/maistra-builder_1.1.Dockerfile
  docker/scripts/install_base.sh
  docker/scripts/install_docs_tools.sh
  docker/scripts/install_go_13.sh
Labels: okay to merge, size/S

#86 Add a missing env var to proxy postsubmit job
  prow/config.gen.yaml
  prow/config/postsubmits.yaml
Labels: okay to merge, size/XS

#85 Define resource requests and limits for ingress
  prow/create.sh
Labels: okay to merge, size/XS

#87 Add cpu limits to all jobs
  prow/config.gen.yaml
  prow/config/postsubmits.yaml
  prow/config/presubmits.yaml
Labels: okay to merge, size/M

#88 Set the Envoy URL for istio 2.0 jobs
  prow/config.gen.yaml
  prow/config/presubmits.yaml
Labels: okay to merge, size/S

#90 Update shellcheck
  docker/maistra-builder_1.1.Dockerfile
  docker/maistra-builder_1.2.Dockerfile
  docker/scripts/install_shellcheck.sh
Labels: okay to merge, size/XS

#91 Add presubmit job to proxy 1.1
  prow/config.gen.yaml
  prow/config/postsubmits.yaml
  prow/config/presubmits.yaml
Labels: okay to merge, size/M
