Repository maistra/test-infra, pull requests merged in 2020-06, with the labels that each got.

#46 Add yq
  docker/maistra-builder_1.2.Dockerfile
  docker/scripts/install_docs_tools.sh
Labels: okay to merge, size/XS

#42 MAISTRA-1472 Add job to build RPMS/containers on istio-operator PRs
  Makefile
  docker/maistra-builder_1.2.Dockerfile
  prow/config.gen.yaml
  prow/config/postsubmits.yaml
  prow/config/presets.yaml
  prow/config/presubmits.yaml
  prow/create.sh
Labels: okay to merge, size/L

#48 Fix builder image hub + set imagePullPolicy to Always
  prow/config.gen.yaml
  prow/config/presubmits.yaml
Labels: okay to merge, size/S

#49 Rename `master` to `main`
  README.md
  prow/config.gen.yaml
  prow/config/postsubmits.yaml
  prow/config/presubmits.yaml
Labels: okay to merge, size/M

#50 Use a unified naming scheme for jobs
  prow/config.gen.yaml
  prow/config/postsubmits.yaml
  prow/config/presubmits.yaml
Labels: okay to merge, size/M

#10 Run integration tests against Maistra/istio
  docker/maistra-builder_1.2.Dockerfile
  docker/scripts/entrypoint.sh
  prow/config.gen.yaml
  prow/config/plank.yaml
  prow/config/presubmits.yaml
Labels: okay to merge, size/L

#51 enable verbosity for unittest
  prow/config.gen.yaml
  prow/config/presubmits.yaml
Labels: okay to merge, size/XS

#52 fix maistra org rename fallout
  README.md
  docker/maistra-builder_1.2.Dockerfile
  prow/config.gen.yaml
  prow/config/branch-protection.yaml
  prow/config/postsubmits.yaml
  prow/config/presubmits.yaml
  prow/config/tide.yaml
  prow/plugins.yaml
Labels: okay to merge, size/L
