Repository maistra/test-infra, pull requests merged in 2021-01, with the labels that each got.

#116 Look for the right yq; Check if it's the correct one
  scripts/check-resource-limits.sh
Labels: okay to merge, size/S

#117 Docs 2.0 should use CI image 2.0
  prow/config.gen.yaml
  prow/config/presubmits.yaml
Labels: okay to merge, size/M

#115 MAISTRA-2060: Point to Red Hat Jira for issues
  .github/ISSUE_TEMPLATE/config.yml
  README.md
Labels: okay to merge, size/S

#118 Add IOR to tide
  prow/config.gen.yaml
  prow/config/tide.yaml
Labels: okay to merge, size/XS

#120 Operator: Use 2.0 image to run 2.0 tests
  prow/config.gen.yaml
  prow/config/presubmits.yaml
Labels: okay to merge, size/L

#119 Added a proxy build image for maistra-2.1
  Makefile
  docker/maistra-proxy-builder_2.1.Dockerfile
Labels: okay to merge, size/M

#121 Setup envoy and proxy jobs for 2.1
  prow/config.gen.yaml
  prow/config/postsubmits.yaml
  prow/config/presubmits.yaml
Labels: okay to merge, size/L

#122 Add lbzip2 to proxy 2.1 image
  docker/maistra-proxy-builder_2.1.Dockerfile
Labels: okay to merge, size/XS

#123 Restore ISTIO_ENVOY_BASE_URL in 2.1 jobs
  prow/config.gen.yaml
  prow/config/presubmits.yaml
Labels: okay to merge, size/M

#124 Experimental job for proxy clang builds
  prow/config.gen.yaml
  prow/config/presubmits.yaml
Labels: okay to merge, size/L

#126 Fix hook RBAC
  prow/cluster/hook_rbac.yaml
Labels: okay to merge, size/XS

#127 Use gcc 9 for proxy 2.1 image
  docker/maistra-proxy-builder_2.1.Dockerfile
Labels: okay to merge, size/XS

#128 Use 2.1 image for envoy 2.1 post-submit
  prow/config.gen.yaml
  prow/config/postsubmits.yaml
Labels: okay to merge, size/M

#129 clang: be more restrict on branches
  prow/config.gen.yaml
  prow/config/presubmits.yaml
Labels: okay to merge, size/S

#130 envoy 2.1-clang post-submit job: use correct image
  prow/config.gen.yaml
  prow/config/postsubmits.yaml
Labels: okay to merge, size/M

#131 proxy post submit 2.1-clang: Use the correct image
  prow/config.gen.yaml
  prow/config/postsubmits.yaml
Labels: okay to merge, size/M

#132 Add tools to compile WASM extension
  docker/maistra-proxy-builder_2.1.Dockerfile
Labels: okay to merge, size/S
