Repository maistra/test-infra, pull requests merged in 2021-11, with the labels that each got.

#182 Fix arguments in merge-upstream-envoy job
  prow/config.gen.yaml
  prow/config/periodics.yaml
Labels: size/S, okay to merge

#183 Add the merge-strategy command line option to automator
  prow/config.gen.yaml
  prow/config/periodics.yaml
  tools/automator-main.sh
Labels: size/S, okay to merge

#184 MAISTRA-2640 Add multicluster integration tests to maistra/istio
  prow/config.gen.yaml
  prow/config/presubmits.yaml
Labels: size/L, okay to merge

#185 Only run servicemesh mc integration tests
  prow/config.gen.yaml
  prow/config/presubmits.yaml
Labels: size/S, okay to merge

#170 No need for promu build
  prow/config.gen.yaml
  prow/config/presubmits.yaml
Labels: size/XS, okay to merge
