Repository maistra/test-infra, pull requests merged in 2021-08, with the labels that each got.

#161 MAISTRA-2579: Install OpenShift tools in 2.1 image
  docker/maistra-builder_2.1.Dockerfile
Labels: size/XS, okay to merge

#162 MAISTRA-2579: Setup an experimental e2e job
  prow/config.gen.yaml
  prow/config/presets.yaml
  prow/config/presubmits.yaml
Labels: size/L, okay to merge

#163 MAISTRA-2579: Missing entrypoint
  prow/config.gen.yaml
  prow/config/presubmits.yaml
Labels: size/XS, okay to merge

#164 MAISTRA-2579: Missing privileged
  prow/config.gen.yaml
  prow/config/presubmits.yaml
Labels: size/XS, okay to merge

#165 MAISTRA-2579: Add OCP 4.8 job
  prow/config.gen.yaml
  prow/config/presubmits.yaml
Labels: size/M, okay to merge

#166 Enable k8s storage
  prow/cluster/crier_deployment.yaml
  prow/create.sh
Labels: size/S, okay to merge

#167 Add gcsweb.maistra.io web server
  prow/cluster/gcsweb/gcsweb_configmap-nginx.yaml
  prow/cluster/gcsweb/gcsweb_deployment.yaml
  prow/cluster/gcsweb/gcsweb_ing.yaml
  prow/cluster/gcsweb/gcsweb_letsencrypt.yaml
  prow/cluster/gcsweb/gcsweb_namespace.yaml
  prow/cluster/gcsweb/gcsweb_service.yaml
  prow/config.gen.yaml
  prow/config/deck.yaml
Labels: size/L, okay to merge

#168 Move the gcsweb files to the main directory
  prow/cluster/gcsweb_configmap-nginx.yaml
  prow/cluster/gcsweb_deployment.yaml
  prow/cluster/gcsweb_ing.yaml
  prow/cluster/gcsweb_letsencrypt.yaml
  prow/cluster/gcsweb_namespace.yaml
  prow/cluster/gcsweb_service.yaml
Labels: size/XS, okay to merge

#169 Add prometheus tests
  docker/maistra-builder_2.1.Dockerfile
  prow/config.gen.yaml
  prow/config/presubmits.yaml
Labels: size/M, okay to merge

#172 Add a merge label to tide
  prow/config.gen.yaml
  prow/config/tide.yaml
Labels: size/XS, okay to merge
