Repository maistra/test-infra, pull requests merged in 2021-07, with the labels that each got.

#155 Use 2.1 images for test-infra jobs
  prow/config.gen.yaml
  prow/config/presubmits.yaml
Labels: okay to merge, size/S

#157 Add tide to xns-informer
  prow/config.gen.yaml
  prow/config/tide.yaml
  prow/plugins.yaml
Labels: okay to merge, size/XS

#158 Update proxy 2.1 image
  docker/maistra-proxy-builder_2.1.Dockerfile
Labels: okay to merge, size/XS

#156 Consolidate 1.8 and 1.9 Dockerfiles
  Makefile
  docker/maistra-builder_2.1-1.9.Dockerfile
  docker/maistra-builder_2.1.Dockerfile
Labels: okay to merge, size/L

#159 Use the same shellcheck version as Istio 1.9
  docker/maistra-builder_2.1.Dockerfile
Labels: okay to merge, size/XS

#160 Revert "MAISTRA-2394 Add build container and jobs for 1.9 rebase"
  prow/config.gen.yaml
  prow/config/presubmits.yaml
Labels: okay to merge, size/L
