Repository maistra/test-infra, pull requests merged in 2022-03, with the labels that each got.

#209 Improve docs
  .github/ISSUE_TEMPLATE/config.yml
  README.md
  docker/README.md
  prow/OPERATING.md
  prow/README.md
Labels: size/L, okay to merge

#211 Tidy jobs
  prow/config.gen.yaml
  prow/config/postsubmits.yaml
  prow/config/presubmits.yaml
Labels: size/XL, okay to merge

#212 Add operator to the list of auto-merge
  prow/config.gen.yaml
  prow/config/tide.yaml
Labels: size/S, okay to merge

#213 Install nodejs 12, needed by proxy
  docker/maistra-builder_2.2.Dockerfile
Labels: size/XS, okay to merge

#214 Add emsdk to 2.2 image
  docker/maistra-builder_2.2.Dockerfile
Labels: size/XS, okay to merge

#215 Added gcc-toolset-*-libasan-devel packages
  docker/maistra-builder_2.2.Dockerfile
Labels: size/XS, okay to merge
