Repository maistra/test-infra, pull requests merged in 2022-02, with the labels that each got.

#188 OSSM-830: New image for 2.2
  Makefile
  docker/maistra-builder_2.2.Dockerfile
  docker/scripts/docker-entrypoint.sh
Labels: size/L, okay to merge

#189 Add jobs for 2.2 branches
  prow/config.gen.yaml
  prow/config/postsubmits.yaml
  prow/config/presubmits.yaml
Labels: size/XXL, okay to merge

#190 Add mdl to 2.2 builder image
  docker/maistra-builder_2.2.Dockerfile
Labels: size/XS, okay to merge

#192 Set Bazel version for 2.2
  docker/maistra-builder_2.2.Dockerfile
Labels: okay to merge

#194 Add rpm-build to 2.2 image
  docker/maistra-builder_2.2.Dockerfile
Labels: size/XS, okay to merge

#195 Attempt to fix the job hanging forever
  docker/scripts/prow-entrypoint-main.sh
Labels: size/XS, okay to merge

#197 Fix proxy images
  prow/config.gen.yaml
  prow/config/postsubmits.yaml
  prow/config/presubmits.yaml
Labels: size/L, okay to merge, don't squash

#199 Fix the volume mount for 2.2 jobs
  prow/config.gen.yaml
  prow/config/presubmits.yaml
Labels: size/M, okay to merge

#198 Add missing pieces to run envoy build&tests
  docker/maistra-builder_2.2.Dockerfile
Labels: size/S, okay to merge

#203 fix(gen-config): adds extra line between files
  prow/config.gen.yaml
  prow/gen-config.sh
Labels: size/S, okay to merge

#204 fix(prow): ensures proper namespace is used in scripts
  prow/create.sh
  prow/update.sh
Labels: size/XS, okay to merge

#201 feat(git): excludes IDE-related folders
  .gitignore
Labels: size/XS, okay to merge

#202 fix(prow): adds missing watch for prowjobs in hook and hologrium
  prow/cluster/hook_rbac.yaml
  prow/cluster/horologium_rbac.yaml
Labels: size/XS, okay to merge

#207 Fix golang in proxy images
  docker/maistra-proxy-builder_1.1.Dockerfile
  docker/maistra-proxy-builder_2.0.Dockerfile
  docker/maistra-proxy-builder_2.1.Dockerfile
Labels: size/M, okay to merge

#208 Add missing xz to proxy images
  docker/maistra-proxy-builder_1.1.Dockerfile
  docker/maistra-proxy-builder_2.0.Dockerfile
  docker/maistra-proxy-builder_2.1.Dockerfile
Labels: size/XS, okay to merge
