Repository maistra/test-infra, pull requests merged in 2022-10, with the labels that each got.

#274 Get default HUB default value quay.io/maistra-dev
  prow/config.gen.yaml
  prow/config/periodics.yaml
Labels: size/XS, okay to merge

#275 Align 2.3 image with upstream 1.14
  docker/maistra-builder_2.3.Dockerfile
Labels: size/M, okay to merge

#277 Adapt the check for yq
  scripts/check-resource-limits.sh
Labels: size/XS, okay to merge

#278 Trigger a new build of 2.3 image
  docker/maistra-builder_2.3.Dockerfile
Labels: size/XS, okay to merge

#266 Remove jobs unit, lint and gen-check for Istio 2.3
  prow/config.gen.yaml
  prow/config/presubmits.yaml
Labels: size/L, okay to merge

#279 Remove operator jobs that migrated to OpenShift CI
  prow/config.gen.yaml
  prow/config/presubmits.yaml
Labels: size/L, okay to merge

#280 Remove 1.1 jobs
  prow/config.gen.yaml
  prow/config/presubmits.yaml
Labels: size/L, okay to merge

#282 Remove xns-informer jobs that were migrated to OpenShift CI
  prow/config.gen.yaml
  prow/config/presubmits.yaml
Labels: okay to merge

#283 Remove API jobs that were moved to OpenShift CI
  prow/config.gen.yaml
  prow/config/presubmits.yaml
Labels: size/L, okay to merge

#286 Fix daily build for 2.3
  prow/config.gen.yaml
  prow/config/presets.yaml
Labels: size/S, okay to merge

#287 Fix daily build for 2.3
  prow/config.gen.yaml
  prow/config/periodics.yaml
Labels: size/XS, okay to merge

#288 OSSM-2175: Allow writes to /rust dir
  docker/maistra-builder_2.2.Dockerfile
  docker/maistra-builder_2.3.Dockerfile
Labels: size/XS, okay to merge

#289 OSSM-2175: Jobs for header-append-filter
  prow/config.gen.yaml
  prow/config/postsubmits.yaml
  prow/config/presubmits.yaml
Labels: size/L, okay to merge

#290 Fix the post-submit job for header-append
  prow/config.gen.yaml
  prow/config/postsubmits.yaml
Labels: size/S, okay to merge

#294 OSSM-2153: adds maistra-2.4 presubmit jobs
  prow/config.gen.yaml
  prow/config/presubmits.yaml
Labels: size/XL, okay to merge

#295 OSSM-2158: Add fpm to 2.4 image
  docker/maistra-builder_2.4.Dockerfile
Labels: size/XS, okay to merge

#296 OSSM-2158: Install mdl to 2.4 image
  docker/maistra-builder_2.4.Dockerfile
Labels: size/XS, okay to merge
