Repository maistra/test-infra, pull requests merged in 2022-06, with the labels that each got.

#222 OSSM-1554 Add prow jobs for 'maistra' branch
  prow/config.gen.yaml
  prow/config/presubmits.yaml
Labels: size/L, okay to merge

#226 Add jobs for Envoy 2.3
  prow/config.gen.yaml
  prow/config/presubmits.yaml
Labels: size/M, okay to merge

#228 Stick with clang 13, the default version got bumped to 14
  docker/maistra-builder_2.2.Dockerfile
Labels: size/XS, okay to merge

#229 Install python 3.8, Envoy tests need it
  docker/maistra-builder_2.3.Dockerfile
Labels: size/XS, okay to merge

#232 Add jobs for Proxy 2.3
  prow/config.gen.yaml
  prow/config/presubmits.yaml
Labels: size/M, okay to merge

#233 Stop setting the CI environment variable in our images
  docker/maistra-builder_2.0.Dockerfile
  docker/maistra-builder_2.1.Dockerfile
  docker/maistra-builder_2.2.Dockerfile
  docker/maistra-builder_2.3.Dockerfile
  docker/maistra-builder_main.Dockerfile
Labels: size/S, okay to merge

#231 OSSM-1554 Add istio-operator jobs for 'maistra-2.3' branch
  prow/config.gen.yaml
  prow/config/presubmits.yaml
Labels: size/L, okay to merge
