Repository maistra/test-infra, pull requests merged in 2022-12, with the labels that each got.

#318 Update prow to v20221205-a1b0b85d88
  docker/maistra-builder_2.3.Dockerfile
  docker/maistra-builder_2.4.Dockerfile
  docker/maistra-proxy-builder_main.Dockerfile
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/prow_controller_manager_deployment.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/config.gen.yaml
  prow/config/plank.yaml
Labels: size/M, okay to merge

#319 Fix the image for the proxy-update-istio job
  prow/config.gen.yaml
  prow/config/postsubmits.yaml
Labels: size/XS, okay to merge

#320 Add image push job for operator
  prow/config.gen.yaml
  prow/config/presubmits.yaml
Labels: size/L, okay to merge

#321 fix: removes unused `multicluster` test label
  prow/config.gen.yaml
  prow/config/presubmits.yaml
Labels: size/XS, okay to merge
