Repository maistra/test-infra, pull requests merged in 2022-11, with the labels that each got.

#297 OSSM-2155: Initial prow jobs for proxy
  prow/config.gen.yaml
  prow/config/presubmits.yaml
Labels: size/M, okay to merge

#298 Add chart update job for 2.3
  prow/config.gen.yaml
  prow/config/postsubmits.yaml
Labels: size/M, okay to merge

#299 Remove jobs for 2.0
  prow/config.gen.yaml
  prow/config/postsubmits.yaml
  prow/config/presubmits.yaml
Labels: size/XXL, okay to merge

#300 OSSM-2154 OSSM-2155: Add postsubmit jobs for envoy&proxy 2.4
  prow/config.gen.yaml
  prow/config/postsubmits.yaml
Labels: size/L, okay to merge

#303 Add a maistra-2.3 operator integ job
  prow/config.gen.yaml
  prow/config/presubmits.yaml
Labels: size/L, okay to merge

#305 OSSM-2239: Jobs for header-append-filter 2.4
  prow/config.gen.yaml
  prow/config/postsubmits.yaml
  prow/config/presubmits.yaml
Labels: size/M, okay to merge

#306 OSSM-2249: Remove jobs for must-gather
  prow/config.gen.yaml
  prow/config/presubmits.yaml
Labels: size/M, okay to merge

#307 Silent the istio-operator_integ-kind-2.3 job
  prow/config.gen.yaml
  prow/config/presubmits.yaml
Labels: size/XS, okay to merge

#308 OSSM-2250: Add jobs for istio-images-centos 2.4
  prow/config.gen.yaml
  prow/config/presubmits.yaml
Labels: size/M, okay to merge

#309 Push images to quay for each maistra/istio PR
  prow/config.gen.yaml
  prow/config/presubmits.yaml
Labels: size/M, okay to merge

#310 Use the maistra-builder image for 2.3
  prow/config.gen.yaml
  prow/config/presubmits.yaml
Labels: size/M, okay to merge

#311 Fix job istio-push-images-2.3
  prow/config.gen.yaml
  prow/config/presubmits.yaml
Labels: size/XS, okay to merge

#312 Attempt to reduce resource requests for 2.4 istio jobs
  prow/config.gen.yaml
  prow/config/presubmits.yaml
Labels: size/M, okay to merge

#315 OSSM-2159: Add job for 2.4 daily images
  prow/config.gen.yaml
  prow/config/periodics.yaml
Labels: size/S, okay to merge

#316 Bump clang to the version used in product build
  docker/maistra-builder_2.2.Dockerfile
  docker/maistra-builder_2.3.Dockerfile
  docker/maistra-builder_2.4.Dockerfile
Labels: size/S, okay to merge
