Repository maistra/test-infra, pull requests merged in 2022-09, with the labels that each got.

#255 Install post-submit job for Envoy 2.3
  prow/config.gen.yaml
  prow/config/postsubmits.yaml
Labels: size/M, okay to merge

#256 OSSM-1932: Add a post-submit job for proxy 2.3
  prow/config.gen.yaml
  prow/config/postsubmits.yaml
Labels: size/M, okay to merge

#258 Add jobs for xns-informers repo
  prow/config.gen.yaml
  prow/config/presubmits.yaml
Labels: size/L, okay to merge

#259 Fix the name of xns-informer repo
  prow/config.gen.yaml
  prow/config/presubmits.yaml
Labels: size/M, okay to merge

#260 Add jobs for api 2.3
  prow/config.gen.yaml
  prow/config/presubmits.yaml
Labels: size/L, okay to merge

#262 OSSM-1967 Add validation istio-images job
  prow/config.gen.yaml
  prow/config/presubmits.yaml
Labels: size/M, okay to merge

#263 Fix images validation job
  prow/config.gen.yaml
  prow/config/presubmits.yaml
Labels: size/M, okay to merge

#264 Remove redundant jobs for Istio and Istio Operator
  prow/config.gen.yaml
  prow/config/presubmits.yaml
Labels: size/XL, okay to merge

#265 Remove istio-images-centos lint jobs
  prow/config.gen.yaml
  prow/config/presubmits.yaml
Labels: size/M, okay to merge

#267 Ignore non-prow statuses on PRs
  prow/config.gen.yaml
  prow/config/tide.yaml
Labels: size/XS, okay to merge

#268 Revert "Remove redundant jobs for Istio and Istio Operator"
  prow/config.gen.yaml
  prow/config/presubmits.yaml
Labels: size/XL, okay to merge

#261 OSSM-743 Add daily community container images build
  prow/config.gen.yaml
  prow/config/periodics.yaml
Labels: size/L, okay to merge

#269 Align 2.3 image with upstream 1.14
  docker/maistra-builder_2.3.Dockerfile
Labels: size/S, okay to merge
