Repository maistra/test-infra, pull requests merged in 2022-08, with the labels that each got.

#238 Rename maistra branch to maistra-main
  prow/config.gen.yaml
  prow/config/presubmits.yaml
Labels: size/M, okay to merge

#239 Add jobs for Istio 2.3
  prow/config.gen.yaml
  prow/config/presubmits.yaml
Labels: size/XL, okay to merge

#240 MAISTRA-2107: Add istio-operator lint job
  prow/config.gen.yaml
  prow/config/presubmits.yaml
Labels: size/M, okay to merge

#243 Disable unnecessary multicluster tests
  prow/config.gen.yaml
  prow/config/presubmits.yaml
Labels: size/XL, okay to merge

#244 Bump golangci-lint to v1.44.0 to match upstream
  docker/maistra-builder_2.3.Dockerfile
Labels: size/XS, okay to merge

#242 Bump prow to the Istio version 1/2
  docker/maistra-builder_2.3.Dockerfile
  prow/config.gen.yaml
  prow/config/presubmits.yaml
Labels: size/S, okay to merge

#247 Increase cpu/mem for operator lint job
  prow/config.gen.yaml
  prow/config/presubmits.yaml
Labels: size/S, okay to merge

#248 Bump prow to the Istio version 2/2
  prow/cluster/cherrypicker_deployment.yaml
  prow/cluster/crier_deployment.yaml
  prow/cluster/deck_deployment.yaml
  prow/cluster/ghproxy.yaml
  prow/cluster/hook_deployment.yaml
  prow/cluster/horologium_deployment.yaml
  prow/cluster/prow_controller_manager_deployment.yaml
  prow/cluster/sinker_deployment.yaml
  prow/cluster/statusreconciler_deployment.yaml
  prow/cluster/tide_deployment.yaml
  prow/config.gen.yaml
  prow/config/plank.yaml
Labels: size/M, okay to merge

#249 Update build-tools image used in jobs for maistra-2.3
  prow/config.gen.yaml
  prow/config/presubmits.yaml
Labels: size/M, okay to merge

#250 Remove job istio-integration-operator-2.3
  prow/config.gen.yaml
  prow/config/presubmits.yaml
Labels: size/L, okay to merge

#252 OSSM-1922 OSSM-1927: Use newer emsdk and binaryen
  docker/maistra-builder_2.3.Dockerfile
Labels: size/XS, okay to merge

#253 OSSM-1926 Add istio-images-centos lint job
  prow/config.gen.yaml
  prow/config/presubmits.yaml
Labels: size/M, okay to merge

#254 OSSM-1926 Add istio-images-centos lint job
  prow/config.gen.yaml
  prow/config/presubmits.yaml
Labels: size/L, okay to merge
