Repository maistra/test-infra, pull requests merged in 2023-03, with the labels that each got.

#334 OSSM-3462 migrate maistra istio push image jobs
  prow/config.gen.yaml
  prow/config/presubmits.yaml
Labels: size/L, okay to merge

#335 OSSM-3352 Add maistra-builder image for 3.0
  Makefile
  docker/maistra-builder_3.0.Dockerfile
  prow/config.gen.yaml
  prow/config/postsubmits.yaml
  prow/config/presubmits.yaml
Labels: size/L, okay to merge

#336 OSSM-3267: mirgate maistra envoy presubmit jobs
  prow/config.gen.yaml
  prow/config/presubmits.yaml
Labels: size/L, okay to merge

#337 Cleanup duplicated istio 2.3 integ jobs
  prow/config.gen.yaml
  prow/config/presubmits.yaml
Labels: size/XL, okay to merge

#338 OSSM-3263: removing daily images periodic prow jobs
  prow/config.gen.yaml
  prow/config/periodics.yaml
Labels: size/L, okay to merge

#340 OSSM-3264: Removing Periodic job from Prow, since it was migrated
  prow/config.gen.yaml
  prow/config/periodics.yaml
Labels: size/M, okay to merge
