Repository maistra/test-infra, pull requests merged in 2023-04, with the labels that each got.

#341 migrate maistra-test-tool plugins to openshift ci
  prow/plugins.yaml
Labels: size/S, okay to merge

#342 ossm-3266: migrate tide config
  prow/config.gen.yaml
  prow/config/branch-protection.yaml
  prow/config/tide.yaml
Labels: size/M, okay to merge

#344 Remove tide
  prow/config.gen.yaml
  prow/config/prow.yaml
  prow/config/tide.yaml
Labels: size/L, okay to merge

#346 OSSM-3716: Remove prometheus
  prow/config.gen.yaml
  prow/config/presubmits.yaml
  prow/plugins.yaml
Labels: size/L, okay to merge

#349 OSSM-3623: Removing integration tests from 2.2
  prow/config.gen.yaml
  prow/config/presubmits.yaml
Labels: size/L, okay to merge

#350 Remove override plugin
  prow/plugins.yaml
Labels: size/XS, okay to merge

#352 OSSM-3728: removing jobs which have been migrated to OpenShiftCI
  prow/config.gen.yaml
  prow/config/presubmits.yaml
Labels: size/L, okay to merge

#356 OSSM-3734: Migrate header-append-filter jobs
  prow/config.gen.yaml
  prow/config/postsubmits.yaml
  prow/config/presubmits.yaml
Labels: size/L, okay to merge
