Repository maistra/test-infra, pull requests merged in 2023-05, with the labels that each got.

#357 OSSM-3270: migrate proxy postsubmit jobs
  prow/config.gen.yaml
  prow/config/postsubmits.yaml
Labels: size/L, okay to merge

#358 OSSM-373x: mirgate api istio operator post jobs
  prow/config.gen.yaml
  prow/config/postsubmits.yaml
Labels: size/XL, okay to merge

#359 Downgrade clang version to 13
  docker/maistra-builder_2.4.Dockerfile
Labels: size/XS, okay to merge
