Repository maistra/test-infra, pull requests merged in 2023-06, with the labels that each got.

#363 Remove 2.1 maistra prow jobs
  prow/config.gen.yaml
  prow/config/postsubmits.yaml
  prow/config/presubmits.yaml
Labels: size/XL, okay to merge

#366 debug postsubmit job
  docker/maistra-builder_2.5.Dockerfile
Labels: size/XS, okay to merge

#373 OSSM-4216 Remove maistra 2.1 builder image
  Makefile
  docker/maistra-builder_2.1.Dockerfile
  docker/maistra-builder_main.Dockerfile
  docker/maistra-proxy-builder_2.1.Dockerfile
  docker/maistra-proxy-builder_main.Dockerfile
Labels: size/L, okay to merge

#374 Add openssl to maistra-builder 2.2
  docker/maistra-builder_2.2.Dockerfile
Labels: size/XS, okay to merge
