Repository maistra/test-infra, pull requests merged in 2023-01, with the labels that each got.

#322 OSSM-2418: Setup post-submit jobs for 2.4
  prow/config.gen.yaml
  prow/config/postsubmits.yaml
Labels: size/L, okay to merge

#323 Bump bazel to 6.0.0
  docker/maistra-builder_2.4.Dockerfile
Labels: size/XS, okay to merge

#325 Add the override plugin to repos
  prow/plugins.yaml
Labels: size/S, okay to merge

#326 OSSM-3021: Create a periodic job that syncs Istio
  prow/config.gen.yaml
  prow/config/periodics.yaml
Labels: size/M, okay to merge

#327 Fix golang installations
  docker/maistra-builder_2.3.Dockerfile
  docker/maistra-builder_2.4.Dockerfile
Labels: size/S, okay to merge

#324 Remove 2.4 istio integ test job
  prow/config.gen.yaml
  prow/config/presubmits.yaml
Labels: size/XL, okay to merge

#329 Add cherrypicker external plugin to maistra-test-tool
  prow/plugins.yaml
Labels: size/S, okay to merge, ok-to-test

#330 Restore istio jobs
  prow/config.gen.yaml
  prow/config/presubmits.yaml
Labels: size/XS, okay to merge
