Repository maistra/test-infra, pull requests merged in 2024-02, with the labels that each got.

#385 Add libatomic to 2.5 image
  docker/maistra-builder_2.5.Dockerfile
Labels: size/XS, okay to merge

#386 OSSM-5883 Change make target to build arm and amd64 image
  Makefile
Labels: size/M, okay to merge

#387 OSSM-4880 Add rpmbuild
  docker/maistra-builder_2.5.Dockerfile
  docker/maistra-builder_2.6.Dockerfile
Labels: size/XS, okay to merge

#389 Fix PR388
  docker/maistra-builder_2.6.Dockerfile
Labels: size/S, okay to merge

#390 Update 2.6 base centos and update libbpf-devel
  docker/maistra-builder_2.6.Dockerfile
Labels: size/S, okay to merge
