Repository maistra/test-infra, pull requests merged in 2024-01, with the labels that each got.

#381 Add maistra-2.6 builder image dockerfile
  Makefile
  docker/maistra-builder_2.6.Dockerfile
Labels: size/XL, okay to merge

#382 fix pkill not found error
  docker/maistra-builder_2.6.Dockerfile
Labels: size/XS, okay to merge

#383 Fix 2.5 image to build proxy
  docker/maistra-builder_2.5.Dockerfile
Labels: size/L, okay to merge

#384 Add java to 2.5
  docker/maistra-builder_2.5.Dockerfile
Labels: size/XS, okay to merge
