Repository maistra/test-infra, pull requests merged in 2025-02, with the labels that each got.

#409 Use go 1.22 in 2.5 image.
  docker/maistra-builder_2.5.Dockerfile
Labels: size/XS, okay to merge

#410 Replace old openssl binary
  docker/maistra-builder_2.6.Dockerfile
Labels: size/XS, okay to merge, ok-to-test

#411 Run 'make uninstall' and copy conf file
  docker/maistra-builder_2.6.Dockerfile
Labels: size/XS, okay to merge

#413 Install go 1.22 along with go 1.20
  docker/maistra-builder_2.5.Dockerfile
Labels: size/S, okay to merge
